<?php
// Initialize the session
session_start();
$is_user = $is_admin = false;
if (isset($_SESSION["acctype"])) {
$is_user = true;
$is_admin = (($_SESSION["acctype"] == 0) ? true : false);
}
?>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="../../blog.css">
<title>Class Guide</title>
</head>
<body>
<a href="../../index.php"><img class="title-img" src="/img/title.png" width="512px" /></a>
<nav class="navbar navbar-expand-md m-dark">
<a class="navbar-brand m-shade" href="../../index.php">EXEDUMP</a>
<button class="navbar-toggler m-light" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
<ul class="navbar-nav">
<li class="nav-item"><a class="nav-link" href="/blog/index.php">BLOG</a></li>
<li class="nav-item"><a class="nav-link" href="/mume/index.php">MUME</a></li>
<li class="nav-item"><a class="nav-link" href="/blog/downloads.php">DOWNLOADS</a></li>
<li class="nav-item"><a class="nav-link" href="../../account.php">ACCOUNT</a></li>
</ul>
</div>
</nav><br>
<div class="container-fluid">
<div class="row">
<div class="col sidebar">
<h3 class="m-shade">Warrior Guide</h3>
<hr>
<p>Written by <a href="https://mumeresource.wordpress.com/guides/warrior-guide/">Mumeresource</a></p>
</div>
<div class="col-sm-10 m-content">
<div class="txt_content">
<p><strong>Introduction</strong></p>
<p>I love the warrior characters. I love that they can take some hits, and be a little more carefree as they play. As a warrior you have the ability to explore areas and test mobs and players and still not worry too much about being able to get away. You have hps and mps to spare. You can eat a bash or two from a high level *Troll*, or you can eat 2 or 3 fireballs still have enough hps and mps to be able to spam to some safer area. For instance I was playing an orc warrior that was backstabbed twice (between 400-500 hps total) I had 18 hps after both backstabs and was still able to get back to the safety of the orkish caves. I dont have to worry if a mage shows up with 2 charmed giants. Any of these things when playing as a thief or as a magic user, is often more serious. You will go low alot faster and you may not have the moves to get somewhere safe. As a caster, if your magical armor or shield go down, you could be dead very shortly. In this guide I will be talking only about traditional MUME warriors. I do not have too much experience with combos, playing as a troll, or as a beorning. All 3 require of the above are played differently than the traditional metal wearing warrior I will be discussing here.</p>
<p>MUME warriors are heavily dependent on equipment to be successful in xp and pk. That is not to say that they are incapable without it, only that life is very much easier with higher damage weapons, and good armor. For the early levels (1-15), warriors can xp pretty fast and take on alot of the smaller and easier mobs. For the other classes this is not so easy. In the early levels, other classes will not be able to do as much damage, or maintain as high of hps. However when you hit higher levels like 16-25 and above, it can take a warrior alot longer to kill a mob than for the other classes. And if the mobs are in groups, the warrior will end up taking alot of hits and going low on hit points, perhaps before he is able to finish off his target. For xp, warriors will find that there are some extremely hard solo mobs or groups of mobs that they themselves cannot manage, but that mages with (quake/charmies), clerics with (blind/sanc/harm/shoot), and thieves with (backstab/shoot) find they can handle on their own. For pk, warriors are quite hardy which makes them a good choice for beginners. The hard part is that it is also sometimes more difficult to kill other players as a warrior. The only damage comes through your weapon hits, and you can see them add up slowly. Other players are not likely to let you hit them to death. You will find that if you play solo you can stand toe to toe against thieves, and casters, even multiple enemies, but your solo xp will be slower, and pk will be harder to find single opponents, ones that stay, or ones that will close themselves in with you without it being a trap.</p>
<p><strong>Race and Abilities</strong></p>
<p>On the puke side you can make whatever race you want. elf, half-elf, human, dwarf, and hobbit. So now you have to decide what kind of a warrior you want to make. Your warrior can fill the role of the buffer or of the hitter/basher. This role can change with the equipment you wear and with the adjustment of mood while in game. I would argue that due to starting base abilities and racial bonuses and maluses, that the best races for warriors on the good side are dwarves and men. The main reason for this is that the other races start with a malus to the strength statistic. I consider strength to be the most important base ability due to its influence on what you can and can’t wield as well as its major contribution to almost all of your warrior skill %s. Because hobbits start with -2 malus to strength, a hobbit will not really ever be able to wield the highest strength weapons without additional strength bonuses, like spells or +strength ring. This will reduce their damage, and carrying capacity, and ability to move without being encumbered. Elves and half elves also start out with -1 malus to strength. Unless you are wanting to make a defensive warrior, or making a role play character, I would stay away from these 3 races for a warrior. For the darkie side you have only the choice of orc.</p>
<p>When creating a warrior in MUME I would max strength, which would give the 18 str for the man, 19 for the dwarf, and 20 to the orc. The second most important stat is dependent on your play style. Conventional warriors will also have max or max -1 constitution. Constitution gives hps and contributes primarily to the endurance skill as well as some weapons skills and your swim skill. I think the third most important ability for warriors, as of spring 2018 is your dex. I would put dex at 14-16 whether man, dwarf or orc. If I am making a defensive warrior I would give him the statistics of a scout, or thief that being max dex, or max dex -1. After dex comes wil, and I would try to keep wil around 12-15 depending on the race. For orc I would try to get 12-14. For dwarf I would put WIL around 14-15 and for man 13-14. But, feel free to play around with it. You can always train it&nbsp; up or down, or reroll your character to something with less or more WIL. WIL influences your endurence skill, a bunch of ranger skills (swim, ride, climb, wilderness), which affect mobility, and it also has minor influence on weapons skills (pound/smite), and bash. Next important is perception (per). It has a huge effect on how well you can learn the track skill and has some minor influence on the warrior skills of parry, slashing and stabbing. It also gives you more chance to <strong>find a gap in armor</strong> during a fight (it is a strike that bypasses armor fully), and may also aid in situational awareness, like noticing sneaking or hidden mobs, etc. If I am not making a thief character, I consider perception the least important base ability and so for many of my characters it is low, in the range of 9-11. The last two abilities are INT and WIS and I would prioritize INT as it contributes to your tracking skill %. You can play around with a stat generator here <a href="http://faine.org/statgen.php.htm" target="_blank" rel="noopener noreferrer">http://faine.org/statgen.php.htm</a></p>
<p>Note that there are people who make warrior combos that have only mage defensive spells. I will not discuss these combos here yet, but they share some similarities with how people may also choose to play shaman. That is using supplemental spells only. Getting medium/low int/wis… in the range of 11-14 and practicing armor, bob, strength, perhaps shield, etc and maybe a low level nuking spell, like burning hands/shocking grasp/ lightning bolt, or earthquake.</p>
<p><strong>Combat</strong></p>
<p>There is general information that you see every time something happens. If you are in combat you won’t see exactly how many hps, mana, and moves you have, but you will get an idea for both you and your enemy.&nbsp; To see the actual numbers you have to get out of combat and check ‘score’. In the middle of combat however you will always see these status updates. For hps you and your enemy can be:</p>
<ul>
<li><strong>healthy</strong>– 100% hps</li>
<li><strong>fine</strong>– 99% hps &gt; 70% hps</li>
<li><strong>hurt</strong>– 69% hps &gt; 45% hps</li>
<li><strong>wounded</strong>-44% hps &gt; 25% hps</li>
<li><strong>bad</strong>– 24% hps &gt; 10% hps</li>
<li><strong>awful</strong>– 10% hps &gt; 0% hps</li>
<li><strong>dying</strong>– 0% hps &gt; -5% hps (at this point you will die unless someone else heals you)</li>
</ul>
<p>for mana you can have</p>
<ul>
<li><strong>burning</strong>– 100% mana &gt; 70% mana</li>
<li><strong>hot</strong>– 69% mana &gt; 45% mana</li>
<li><strong>warm</strong>– 44% mana &gt; 25% mana</li>
<li><strong>cold</strong>– 24% mana &gt; 10% mana</li>
<li><strong>frozen</strong>– 10% mana &gt; 0% mana</li>
<li><strong>icy</strong>– 0% mana &gt; -5% mana</li>
</ul>
<p>for movement points you can have</p>
<ul>
<li><strong>tired</strong>– 50% &gt; 25% mps</li>
<li><strong>slow</strong>– 24% &gt; 10% mps</li>
<li><strong>weak</strong>– 9% &gt; 5% mps</li>
<li><strong>exhausted</strong>– 5% &gt; 1% mps</li>
</ul>
<p>Mood management is key in battles. You can choose your mood from the following. You do not have to move in succession, but can change directly from wimpy to aggressive if you choose. There is a slight delay in the actual changing of your ob and pb, but not longer than 1 round of hitting or so.</p>
<ul>
<li><strong>wimpy</strong>– the most parry bonus (pb) and least offensive bonus (ob). If you are tanking, this is the mood you want to be in.</li>
<li><strong>prudent</strong>, <strong>normal</strong>, <strong>brave </strong>(in order of increasing ob )- these are middle of the pack and worth trying out. On some mobs and players, you may find a sweet spot where you are not getting hit but you are still hitting.</li>
<li><strong>aggressive</strong>– this is max ob without being berserk</li>
<li><strong>berserk</strong>– this is max ob and least pb. You will hit extremely hard, but also be taking more hits and damage due to lower pb, and <strong>you cannot flee if you are berserk</strong>. Be careful with this one. If you go berserk and you are versus a player or a mob, or a group, and they don’t flee out, you will be there until you or they are dead. I would use this if I was blocked in a one roomer, or otherwise extremely desperate and almost certainly going to die anyway.</li>
</ul>
<p>Most people usually end up using aggressive and wimpy and forgetting about the rest. There may be hidden gold in the forgotten moods…</p>
<p>All of mume is based on combat. Even casters wield weapons and hit and take hits. As a warrior the physical combat is your bread and butter. This information is out there on some other websites, but here are some of the basic things you need to understand about combat. First are the battle messages. You enter a room and enter a command to kill a mob.</p>
<p>The battle messages will tell you many things, including:</p>
<p><span style="color:var(--color-neutral-600);">-who you are fighting, (unless your are blind or in the dark in which case you will see </span><strong style="color:var(--color-neutral-600);">something/someone</strong><span style="color:var(--color-neutral-600);">), </span></p>
<p><span style="color:var(--color-neutral-600);">-what kind of weapons you and your opponent are wielding (</span><strong style="color:var(--color-neutral-600);">pierces, slashes, pounds, cleaves, stabs, shoots, smites</strong><span style="color:var(--color-neutral-600);">) etc., </span></p>
<p><span style="color:var(--color-neutral-600);">-how hard each hit is (</span><strong style="color:var(--color-neutral-600);">barely, lightly, regular (no modifier), hard, very hard, extremely hard</strong><span style="color:var(--color-neutral-600);">), </span></p>
<p><span style="color:var(--color-neutral-600);">-where each hit landed (</span><strong style="color:var(--color-neutral-600);">head, arm, leg, hand, body, foot</strong><span style="color:var(--color-neutral-600);">, etc.), </span></p>
<p><span style="color:var(--color-neutral-600);">-and relative hps left for you and for your opponent, i.e. ‘</span><strong style="color:var(--color-neutral-600);">tickles it</strong><span style="color:var(--color-neutral-600);">‘ means many hps left, but ‘</span><strong style="color:var(--color-neutral-600);">shatters it</strong><span style="color:var(--color-neutral-600);">‘ means there are not many hps left. </span></p>
<p>You should pay attention to these messages. They tell you where you are getting hit. If you are wearing leather boots, you will be getting hit on your feet alot harder than your metal breastplate. If your opponent is using a pounding weapon and you are wearing plate, he will be doing more damage to you when he hits the metal armor. If he is wielding a spear, he will be doing more damage if you are riding, and he will be waiting for you to try to hit first so he can keep at bay. These battle messages can tell you alot, and inform you if you should change some tactics or be doing something different.</p>
<p><span style="color:var(--color-neutral-600);">There are also messages if you or your enemy </span><strong style="color:var(--color-neutral-600);">parry</strong><span style="color:var(--color-neutral-600);"> or </span><strong style="color:var(--color-neutral-600);">dodge</strong><span style="color:var(--color-neutral-600);"> attempted hits, or if you </span><strong style="color:var(--color-neutral-600);">keep your enemy at bay</strong><span style="color:var(--color-neutral-600);">, or </span><strong style="color:var(--color-neutral-600);">bash</strong><span style="color:var(--color-neutral-600);"> it or </span><strong style="color:var(--color-neutral-600);">kick</strong><span style="color:var(--color-neutral-600);"> it, or if you or it become affected by some kind of </span><strong style="color:var(--color-neutral-600);">poison</strong><span style="color:var(--color-neutral-600);">. If you are fighting against a caster and they </span><strong style="color:var(--color-neutral-600);">begin casting</strong><span style="color:var(--color-neutral-600);"> you will also see that message, and if the spell is cast, you will see your enemy utter </span><strong style="color:var(--color-neutral-600);">some strange word or words</strong><span style="color:var(--color-neutral-600);">. And depending on the spell, you may be hit by offensive spells.</span></p>
<p>You can learn what kind of a battle it will be from the first few battle messages. As soon as you can tell that you are in a losing fight you should get out. Fights vs mobs should never be loosing fights. If you are getting shattered in the first few hits, you should be tanking it and other group members should be nuking it. If you are alone, you should get out. You won’t last long against shatters, and the mob you are fighting needs to die or you will. Fights vs other players will mostly be close fights and you will often end on low hps if it was any kind of a fair fight.</p>
<p><strong>Parry split-</strong> This is also a good thing to understand. Your dodge bonus stays the same no matter what. (I personally think it should be the other way around, that dodge should be split between opponents…) Your parry bonus(pb) is divided amongst and split between your attackers. If you are fighting 3 mobs, your pb is divided by 3 and you then effectively have your pb divided by 3 vs each mob. This means that you are taking more hits and harder hits than if you took them on one at a time. If you are in battles with groups it is good to try to take out the weakest mobs first. They may take only 1 or 2 hits to kill, but your pb increases drastically and with it your ability to take the hits and ultimately survive. For example you are in a battle with a werewolf and 2 snakes. Your pb is now divided by 3. If you are committed to the battle, your priority should be to kill the snakes first. Target the snakes, and as they die one by one your pb will be divided by 2 and then by 1. These are drastic increases, and you will be parrying more hits and taking less damage with each hit as the battle continues, and all it took was the 1 or 2 hits on the snakes. On the other hand, if you continue to focus on the werewolf, it will take much longer to kill than the snakes, and your pb will be divided by 3 for the entire battle, meaning you take more and harder hits for the duration of the fight.</p>
<p><b>Skills and Practices</b></p>
<p>Upon creation of your character you will get practice sessions (pracs) to spend. I like to put 6 pracs into warrior guild every level until level 10 or so. 2 into your weapon of choice, 2 into parry, and 2 into endurance per level. The other practice sessions should go into swim(3), climb(3), bandage(3), ride(10), wilderness (max), dodge (5-10 pracs, dependent on preference and play style). At level 10 or so, you should start to put practice sessions into bash until it is maxed out. At level 15 try to get pick(3-4 pracs/30%), some cure light (3-4 pracs/30%), and bless (3-4 pracs/30%). At legend, you can play around with where you spend your practice points. I would spend anywhere from 41 to 50 pracs in endurance at legend, around 10 pracs in dodge, 3-5 pracs pick, max wilderness, track (whatever it takes to get 70%-90% depending on your choice and play style), superb in weapon skill (usually this is max, or max -1 or -2 points. Max bash. I would get parry to the closest 5%. If you max it and it is 98%, I would train it down to 95% and put the pracs somewhere else. Your pb will stay pretty much the same. You will probably want some rescue. 5 pracs is enough to start with. If you group often you might consider getting more. At legend I like to have close to 100% (10 or 11 pracs) in ride if human. If you are a dwarf I would still get some, but maybe only to 70% or so. Swim and climb at whatever you want.&nbsp; The good races have more pracs so they can more easily reach 80% or 90% that is 8 or 9 pracs each. For evil characters I would leave it around 50% – 70%. Bandage I would get 30% to 40% (3-5 pracs at legend level). After these basics, it is up to you to practice into other things. You can experiment with the missile skill. 6 pracs can get you 50% skill and can be worth it to help boost damage. You could also invest in some other spells like detect magic, strength, protection from evil, etc. Just watch what it does to your ob, db, pb, hps etc. If you sink 5 or 6 pracs into strength spell, you may see a drop in some things, but when the strength spell is up you will also see db and ob rise. So it is a trade off in most cases for what you lose and what you get. You will have to decide and find your balance.</p>
<p>Skills outside of warrior guild that I have found most useful and fruitful (in no particular order) are cure light, bless, pick, dodge, missile, envenom, attack, detect magic.</p>
<p>I would like the kick skill to work. Some people swear by it. They use it mostly for finishing off incapacitated enemies. It won’t miss on them. It could be extremely valuable for interrupting spell-casting instead of fleeing out of the room, but I think I would have to get it up to 90% or so for it to work well. For the amount of pracs you would spend (20 or so), I doubt that it would be worth it. For killing incapacitated enemies though, 1 – 3 pracs should be enough.</p>
<p><strong>Methods and Advice<br>
</strong></p>
<p>This is a section about what has worked for me, and what has not. I am not a super experienced player, so my commentary….well, it is what it is.</p>
<p><strong>Weapon choice-</strong> For pk I would try to find the highest damage, most ob weapon I can get a hold of. I would even say I value good 20ob high damage smiting weapons over the 20ob weapon and +20pb shield alternative. For xp though, I would choose either a spear and shield, or sword and shield. For sword and shield there are many options. You could go for high defense and get the +10pb swords (dunadan blade and ebs/dark broadsword) or for higher offence and go for +20ob steel claymore. Swords give alot of versatility for solo or group, you can take multiple mobs or just one, you can choose high defence or high offence. If you choose a spear you would be mostly solo and relying on keep at bay to get your hits. That means high ob because, landing a keep at bay depends on high ob. You want to flee out and go back in or for the mob to follow, and keep at bay again, giving you repeated hits on your target without them hitting you. It is possible to take on some hard mobs this way, though it is not always this easy or simple.</p>
<p><strong>Hit/Flee has been a tactic that has worked</strong> very well for me. Especially<strong> if you have the higher damage weapon.</strong> Basically you will be trading hit for hit, and if your weapon hits harder you will come out on top in the fight. As a warrior you often dont want to hang around too long in a room. Casters will try to cast and get off spells, mobs and other players will try to land a bash on you, and generally it is not a good idea to just sit in the same room. You do not want to eat spells, or bashes. However, you may need to sacrifice and gamble on eating a spell or a bash if you yourself are trying to land one. Choose your time wisely, and try to get as much damage in the bash as possible. It may be your chance to end them. People hit/flee as a matter of course. If you are going to do it anyways in pk, you might as well use a smiting weapon while you are at it.</p>
<p>I have tried to have kick work for interrupting spellcasting on mobs, but I could not trust it to always land in time, and if you cannot trust it to land, thats a dangerous gamble to get into with a caster who may end your life if their spell lands. In my opinion it is not worth the pracs you would have to sink into it to make it reliable. I would rather get a second weapon skill or more rescue. If you max it though…maybe it lands in time every single time… or use it only on incapacitated enemies.</p>
<p><strong>Equipment</strong></p>
<p><strong>Armors</strong></p>
<p>As for equipment, usually money can get you a pretty good set.</p>
<p><strong>Forest green cloak(+5 move regen, +5 db)-</strong> can be found close to Grey Havens, or on Eoggha, or sometimes in the elven hunters hut east of Rivendell, or Mountains of Mirkwood corpse, or in skeleton near Mrak, or for sale for 3 gold or so in most shops.</p>
<p><strong>Majestic golden mantle(+5 move regen, +3ob)</strong>– you have to kill majestic lion in Brush.(very hard for a solo warrior) Then have 50 gold ready and go to Fornost tailor. Give him majestic golden fur and he will automatically take 50 gold and make majestic golden mantle for you.</p>
<p><strong>Fine metal breastplate</strong>– loads on the old wight e of Bree and also on Gumak in Redhorn caves. Use it and sell the rest to make money.</p>
<p><strong>Gilded round shield(+25pb)-</strong>&nbsp;sometimes it loads on the gilded ghost east of Bree. You can get the shield off of him or in the armory in Bree or Rivendell for 13 gold or so. Warrior with pick/bash and climb can get to the mob pretty easily. Others without bash/break door have to find a key and go through some muddle.</p>
<p><strong>Bejewelled shield(+30pb)</strong>-is rarely for sale in Rivendell. It can be bought for 50 to 110 gold depending on condition. Or can be looted from Bloodwight.</p>
<p><strong>Metal Wall Shield(+27pb)- </strong>easily obtainable. It loads in hidden bn eq east of abr and south of brolg.</p>
<p><strong>Smooth black boots(-move cost on foot)</strong>– for when you are on foot, load in skeleton south of troll warrens,</p>
<p><strong>Black padded boots(-move cost on foot and a little armor)</strong>– can be looted from blood-thirsty orcs in dunland, or from corpse on a path heading south from the main road through the Misty Mountains.</p>
<p><strong>Great Helm- </strong>can be looted from huge olog in troll caves south ABR. But it and the other <strong>fine metals</strong> can be bought for 10 gold a piece or so. That is <strong>gloves</strong>, <strong>vambraces</strong>, <strong>greaves</strong>, and&nbsp;<strong>boots</strong>.</p>
<p><strong>Spiked metal helmet</strong>-almost as good as great helm, can be looted from orc warg-riders S of Rivendell and N of Brolg.</p>
<p><strong>Broad silver belt-</strong> can be looted from Wight captain. Solo thief or mage with charmie or a group of two legends can get it. Sometimes its for sale at Rivendell for 25 gold.</p>
<p><strong>Gleaming belt</strong>– butcherd from scaly beast, or for sale sometimes for 333 gold.</p>
<p><strong>Picks</strong>– Blue mountains for sale, but must be a citizen to go down past the guards. For sale in Tharbad. Just watch out for enemies. Loads on some mobs like trapper N of Tharbad, creature in underground cavern southeast of Lorien, orc assassins inside of noc and wnoc. Those are the most easily accessible ones that I know of.</p>
<p><strong>Herbal Kit</strong>– can be found for free N of Forlond, or on hillman chief, Niuldor corpse or for sale in shops. Pretty easy upgrade can be obtained from Niuldor e of Anduin river. Get elderberries in Fanghorn Forest. 1 is enough. They decay after something like a real life day. Go to librarian in Lorien. Say or ask librarian parchment. Take parchment Niuldor, Give parchment, wait, and give berries. He may reward you with kit upgrade or with gold. For orcs/bns, you have to bring rare herblore to WNOC shaman guildmaster. I think antidote/arachnia lores work. Then you have to bring him some rare herb. Ginseng/Foxtail or some such.</p>
<p><strong>Ruby</strong>-can be bought in Forlond, Rivendell, and Lorien jewelers.</p>
<p><strong>Weapons</strong></p>
<p>The good weapons can be tougher to come by, or alot more expensive. As a warrior you will only want the best.</p>
<p><strong>Spears-</strong> I like using spears on warriors. I love keep at bay and spears do extra 25% damage vs targets who are riding. Keep at bay depends on ob so I would stick with the highest damaging most ob weapons</p>
<p style="padding-left:30px;"><strong>Blackened Spear(+20 ob, -5 pb)-</strong> easier to buy than to make in my opinion. To make it you need to kill Nagash e of Noc and w of carrock. Not sure if it is soloable, but it is behind a door that takes something like 24 or 30 strength to open. Loot his black metal staff. Then you have to find a glittering spearhead. It loads on some corpses around vale, but rarely. Then you need a piece of mithril found only in moria. If you have all you can go to Angdil in Rivendell or Grachalg in DT as darkie and “mend spearhead” and he will make blackened spear. Or you can buy it for 84 gold or so. It is usually available in Rivendell Armory.</p>
<p style="padding-left:30px;"><strong>Giant Spear(+15 ob, -5 pb)-</strong> still good damage, and you dont have to enchant it to get the 15 ob. It loads on a level 15 or so mob in the misty mountains, but is usually for sale in most shops for 1 gold or so.</p>
<p style="padding-left:30px;"><strong>Steel-tipped spear/Steel shafted spear-</strong> they are ok options, but in my opinion not as good as the above. Steel tipped spear has +20ob <strong>only if you get it enchanted</strong>, and not as much damage as giant spear. Steel shafted has good damage but only +10 ob and only if you get it enchanted, and not as much damage as giant spear. Not worth it in my opinion, but they are good options if you want spears and lack 18 strength for the better weapons above.</p>
<p><strong>Swords-</strong> for those more defensively minded. Usually give 0pb or +5pb, or if you can get engraved broadsword or dunadan blade +10pb. Faster but not as damaging. Good for tanking, and taking on multiple opponents at a time. This class of weapons also has the most legendary weapons.</p>
<p style="padding-left:30px;"><strong>Steel claymore(+20 ob, 0 pb)-</strong> I think you can get it from Saruman in exchange for power magic items. I sometimes see them for sale in Rivendell or Bree. They can be bought for 50 gold or so.</p>
<p style="padding-left:30px;"><strong>Jagged edged scimitar(+15 ob, 0 pb)-</strong> unenchantable. If you cant afford the steel claymore, this can be bought for 1 gold or so in Bree or Rivendell.</p>
<p style="padding-left:30px;">Other swords <strong>falchion</strong>, <strong>broad scimitar</strong>, <strong>serrated scimitar</strong>, <strong>longsword</strong>, etc. must all be enchanted to be as good as or better than <strong>jagged-edged scimitar</strong>. If not they are worse. As already mentioned, if you are tanking then <strong>Engraved Broadsword(ebs)</strong>, or <strong>Dunadan Blade&nbsp;</strong>are good, but they are difficult to get and rarely on sale in shops for 40-50 gold.&nbsp; Both however do less damage than jagged-edged scimitar.&nbsp;<strong>EBS</strong> can be looted from Bloodwight, and <strong>Dunadan Blade</strong> from the kraken in Old Fornost.</p>
<p><strong>Maces/Hammers- </strong>this is an extremely popular weapon choice because it does extra 25% damage on metal armor. Alot of people wear metal armor including casters.</p>
<p style="padding-left:30px;"><strong>Ornate warhammer(+20 ob, -5 pb)-</strong> this is probably the most sought after crushing weapon. It can be looted from a Muranog in moria, or sometimes bought in shops for 120 gold or so.</p>
<p style="padding-left:30px;"><strong>Engraved Warhammer(+20 ob, -5 pb)-</strong> rarely in shops, sometimes loads on spirit knight, some south and west of Morthan Blacksoul on Greenway. Less damage than ornate, but almost as good, and much easier to aquire. Easy for thief, doable for warrior with decent eq. Kill all the slaves first. Climb up and rest until full. Then hit/flee or bash knight. When I beat it on warrior I was smiting (may have made the difference) and I ended pretty low.</p>
<p style="padding-left:30px;"><strong>Heavy Morningstar(+20 ob, -10 pb if enchanted)-</strong> cheap, but its not always easy to get a max enchant. Ask around and get it enchanted if an enchanter is on.</p>
<p><strong>Axes-</strong> axes are a decent weapon choice, especially for dwarves who gain +5ob if they are on foot wielding axes. They are fast and do large amounts of damage. They are effective against anything wood. These are sometimes the best weapons that some orcs can get their hands on.</p>
<p style="padding-left:30px;"><strong>Mighty Dwarven Axe(+15 ob, -5 pb)-</strong> known as mda. will sell for around 13 gold in shops. It is fast to swing and does more damage than most other weapons. Can be looted from dwarven tombs in eregion east of oie and west of tall orc and north of the road.</p>
<p style="padding-left:30px;"><strong>Darkened Orkish Axe(+15 ob, -5 pb)-</strong> slightly slower than mda, but does more damage, and in my opinion is the better weapon. It can only be looted by darkies from a tree in fanghorn. It is in the middle of the forest and all north. Darkies beware when entering this forest.</p>
</div>
</div>
</div>
</div>
</body>
</html>
