<?php
// Initialize the session
session_start();
$is_user = $is_admin = false;
if (isset($_SESSION["acctype"])) {
$is_user = true;
$is_admin = (($_SESSION["acctype"] == 0) ? true : false);
}
?>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="../../blog.css">
<title>Class Guide</title>
</head>
<body>
<a href="../../index.php"><img class="title-img" src="/img/title.png" width="512px"/></a>
<nav class="navbar navbar-expand-md m-dark">
<a class="navbar-brand m-shade" href="../../index.php">EXEDUMP</a>
<button class="navbar-toggler m-light" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="collapsibleNavbar">
<ul class="navbar-nav">
<li class="nav-item"><a class="nav-link" href="/blog/index.php">BLOG</a></li>
<li class="nav-item"><a class="nav-link" href="/mume/index.php">MUME</a></li>
<li class="nav-item"><a class="nav-link" href="/blog/downloads.php">DOWNLOADS</a></li>
<li class="nav-item"><a class="nav-link" href="/tarkov/index.php">TARKOV</a></li>
<li class="nav-item"><a class="nav-link" href="../../account.php">ACCOUNT</a></li>
</ul>
</div>
</nav><br>
<div class="container-fluid">
<div class="row">
<div class="col sidebar">
<h3 class="m-shade">Warrior Guide</h3>
<hr>
<p>Written by <a href="https://mumeresource.wordpress.com/guides/zaugurz/">Mumeresource</a></p>
</div>
<div class="col-sm-10 m-content">
<div class="txt_content">
<p><strong>Introduction</strong></p>
<p>I have not seen a guide for Zaugurz orcs and so I thought I would write some things up that I would have liked to have known before starting. Of course, the Zaugurz are very difficult to play. I would still maintain that a BN character is harder to level to legend, but at least once you are legend, life gets easier for a BN.&nbsp; There are friendly mobs and safe places. Life will never get any easier for a Zaugurz because every single mob outside of the Zaugurz caves is aggressive to you. It will never get any easier because you are alone. Usually only already experienced players will make a Zaugurz orc, or a BN for that matter, but still I thought I would write some things up that can help a newer player make a Zaugurz character, hopefully without the frustration of a lot of deaths.&nbsp; I am not any great or experienced player, but I have made several Zaugurz orc characters, and so here is a brief introduction.</p>
<p>As a Zaugurz, you have no mana, no mounts, no shops, and one rent place, that is the Zaugurz caves, also sometimes called ZOC. It is in general, the safest place for a Zaugurz. However if you are low on hps, or moves and players know it and know you are in the Zaugurz caves, they may just come for your pathetic life.</p>
<p>You will start out with no equipment, in the middle of an active pk (player killing) zone surrounded by aggressive and tracking mobs that can kill you in just 2 or 3 hits. There is no ‘pray newbie kit’ and the odds are that you may be the only Zaugurz online. Other enemy player characters will track throughout this area, so even leaving the Misty Mountains will mean that you could be being tracked. And at level 1 you do not even have enough moves to get out of the Misty Mountains in one sprint. The first levels are the most difficult because your mobility is so low. The only good news for a lowbie Zaugurz is a session played without dying.</p>
<p><strong>Warrior or Thief&nbsp;</strong></p>
<p>The Zaugurz have only three guild masters: Ranger, warrior, and thief guild masters. That means two classes, or some kind of combo of the two. Many Zaugurz choose the life of thief because it is the easier life. Thieves can more easily kill harder mobs solo, or even groups of mobs due to backstab and sneak. This means they have a greater ability to get much better equipment solo. Thieves also are able to level up extremely fast after they get a good working backstab at around level 16-18. If however an enemy player character knows you are around, beware, because the fight will not be easy. The warrior on the other hand has greater survivability in terms of amount of health, moves, ability to take some hits, as well as deal some consistent decent damage, but they do lack the burst damage of a thief, and often rely on groups for both xp and pk. Warriors are also a far more equipment dependent class, and as a warrior you do not have as great of an&nbsp; ability to get the best equipment by yourself due mostly to a lack of shops.&nbsp; But <strong>if</strong> you have some good eq, you can become quite a force for the tribe.</p>
<p><strong>Thief Base Abilities</strong></p>
<p>As thieves are the more popular choice for most Zaugurz, I will discuss them first. Your most important stat is dex and maximum dex is non-negotiable in my opinion. If you want to xp up faster, I would play a pure thief with as high of stat %s as you can get and that means max per too. If you just want to get up to legend level and then stab other players online, you can get away with lower perception maybe as low as 16. However, even as a combo, pretty pure stats are desirable because it means more space to practice outside of your guild while still maintaining higher class skill percentages than having lower thief skill percentages and then also trying to practice some warrior skills. What this means is that whenever you practice a skill from another guild, it will raise the percentage of that skill, but will lower the percentage of the skills not of that same guild. For example, if you have 105% in backstab and dodge, and then you put 30 practice sessions in bash which is a warrior skill, your backstab and dodge percentages might drop to 102 % or 103 %, while your bash skill % increases. So a higher max percentage of thief skills will let you practice more warrior skills and still maintain things like sneak and backstab above 100%.</p>
<p>A decent set of base abilities would be something like&nbsp; 18,6,7,18,16,9,18 (Str, Int, Wis, Dex, Con, Wil, Per) With this you can stab hard mobs without failing as much. This is without training. So you could always train down 2 per and get 2 str or 2 more con easily. If you wanted to pk you could train more heavily into some warrior things like bash. As noted above, your max dex and per give you higher thief percentages which will allow for more pracs outside of your guild while still maintaining a higher thief skill percentage.</p>
<p>Or you could make something like a pk thief intended mostly for pk, but you may find yourself failing sneaks and backstabs against harder mobs. 18,6,6,18,17,10,17 (Str, Int, Wis, Dex, Con, Wil, Per)&nbsp; With this you could still train str to max and get con up to 18. This would be a really hardy thief with good moves and hps as well. But your thief percentages will be lower and will not give you too much room to practice outside of your guild.</p>
<p><strong>Thief Skills- </strong><strong>(what makes you a thief)<br>
</strong></p>
<p>Backstab, dodge, piercing, sneak, attack (if you are a thief, get these to max… no matter what)</p>
<p>Missile, envenom, escape, pick, hide (choose what you want and how you want to play)</p>
<p><strong>Ranger Skills- </strong></p>
<ul>
<li><strong>wilderness(max it at 27 pracs)-</strong> this is non-negotiable. As far as I know it reduces your movement cost on foot and the need for food and water.</li>
<li><strong>track-</strong> its easy to get high as a thief, i would take no less than 81%, or more if you want.</li>
<li><strong>climb (minimum of 70%-100%)-</strong></li>
<li><strong>swim (minimum of 70%-100%)-</strong></li>
<li><strong>bandage (3 to 5 pracs, or 30%+)-</strong></li>
</ul>
<p><strong>Warrior Skills-</strong></p>
<ul>
<li><strong>endurence (1-3 pracs)-</strong> this will give you hps and hps regen, and help with wounds</li>
<li><strong>parry-</strong> I would get 3 to 5 pracs, but it is up to you how much to practice. the more you practice the more pb (parry bonus) you will get, which will make you quite defensive. However, the more you practice parry, the more all of your thief skill percentages will drop including dodge, and dodge is generally more valuable than parry, so be careful with how much you practice parry. I have seen that per every 5% in this skill I get +1 pb. So the first 3 practices may give you 40% or so in parry which would be +8 pb. 50% in parry would give you +10 pb. etc. I would practice it to as much as it can give you without dropping your dodge skill %.</li>
</ul>
<p>If you want to be more of a <strong>combo</strong> or <strong>war-scout</strong> then you may want to also practice into</p>
<ul>
<li><strong>bash(try to get 75%)-</strong> this skill gives you the ability to bash your opponent. While bashed, your opponent is unable to do anything, and their defenses are lower. While they are bashed is the perfect time to end their life, or get away yourself. Bash success depends largely on your ob (offensive bonus) and your bash skill %. There are some who feel that scout/thief classes often have a very fast bash and some attribute this to their naturally high dexterity, while others attribute it to less total weight carried compared to warriors. The main idea with bash though, is to bash your opponent and then get off 3 or so arrows in the space of the bash and so do some burst damage to your target.</li>
<li><strong>weapon skill- </strong>some thieves practice a warrior weapon skill. This would give you more of an ability to fight with people using something other than backstab, piercing weapons, and bows. If you do this you will want to try to have at least 18 strength with training in order to wield the most damaging weapons, or else you will have to settle for the lighter, lower damage weapons. The more you practice, the more your weapon skill ob goes up, the more likely you are to hit with the weapon and land a bash while wielding it. As with parry, 5% weapon skill gives +1 ob in that weapon skill.</li>
</ul>
<p><strong>some comments-</strong> Keep in mind that the more practices you sink into warrior skills, the more of a combo you become. The nice thing is that you can move your practice points around until you find a good practice set for your play style. If you still want to be a scout, you will need to practice in such a way that your scout skills backstab and sneak do not go below 101%. &nbsp;I have found that against mobs at least, higher percentages can make a huge difference in the success of a backstab. I believe this is because mobs have a certain awareness/perception/search skill and after the first backstab has been landed on them they will flush the room they are in every so often or they have heightened awareness. Even when you have not landed a backstab it seems as if&nbsp; mobs reveal or flush every so often. Or, it might work in such a way as your percentages and abilities in sneak and backstab are measured against the mobs awareness, or search skill etc. and with lower percentages you will find yourself failing sneaks/backstabs more often against mobs. Against players though 101 % is fine because players do not always perform reveals/flushes or practice awareness. If you don’t care about backstab, loose it and become a full combo, practicing heavily into endurence, parry, dodge, bash, and your weapon skill of choice. Enjoy finding out what works for how you designed your character.</p>
<p><strong>Warrior Base Abilities</strong></p>
<p>Now for warriors. Much that is said here can be seen in the general guide on warriors. One of the main deciding factors in your stats is how good you want your track skill to be. The track skill is based on Per and Int, and neither are really that important for a warrior. So to get 100% track, you will have to give on some stat that I would value more like dex or wil, or con. For me it is not worth the pay out to have 100% track as a warrior. As a warrior max strength is non-negotiable as far as I am concerned. You could choose to give up con for a higher track percentage. This will mean lower hps, endurance % and lower conc/smiting %. You can lower your dex which will mean lower dodge bonus, and lower dodge skill percentages, and lower moves, and a little lower move regen. (I saw a chart that may or may not be accurate that shows dex as giving some move regen.) Or you can give up some wil which will lower your endurance skill %, and your WILDERNESS skill %. I play on 250-350ms (usually) link and slow track is just too slow to track down for a kill. What I use track for is checking bottlenecks, entrances, or finding fights, rarely for finishing fights. I have found that for my orc warriors, around 70% is enough to check who has been through a room recently. Also, as my Zaugurz gains levels I find that I desperately value moves and hps, offence and defense above all else, and my reasoning has turned to thinking what is the point of track if I cannot fight or move, and so my priorities have shifted towards not valuing track on my warrior characters. When I say not valuing, I mean being ok with 71% or 81% or 91% or whatever I have to be ok with.</p>
<p>With that in mind, my optimal orc warrior stats would be something like 20,6,6,16,19,13,12 or 20,6,6,15,19,14,12. or 20,7,7,15,19,13,13 These would give around 85% in track with max practice sessions. You could put whatever amount of practices you wanted in it and get it to 85% or 81% or 71%. These builds would have high percentages in everything else. I can train per or wil down and con up to max at 20. Or if you really want, you can reroll to something with max con. Or your can reroll something with higher per to get more track or higher dex to get more dodge, or higher thief skills, etc. etc. I tend to prioritize strength over con on all my thief and warrior characters. I do this for skill percentages in warrior guild, skill % in wilderness which relies on strength over con. I value str because it increases carrying capacity, max ob, bash heavy doors etc and in general, of more value to me than lost 1 or 2 % in the warrior skills of endurance, smite and concussion weapons. I have not tried high con/max con thieves or warriors though, so my feelings are just that. I can still train con up to 20 so the only hps lost is the lost 1 or 2 % in endurance which may be around 10 or so hps.</p>
<p><strong>Warrior Skills (what makes you a warrior)<br>
</strong></p>
<p><strong>Weapon skill-</strong> (get it superb) I would choose stabbing because their is pretty easy access to a good high damage non-enchantable +15 ob spear nearby(giant spear). Spears are eff vs riding and give you a good chance at the first hit.</p>
<p><strong>Endurance-</strong> get it to 91% or more depending on your style.</p>
<p><strong>Bash-</strong> (max it) this is one of the main things you do</p>
<p><strong>Parry- </strong>i doubt you can get it to 100%, I would just leave it at 95%, but this is your defence.</p>
<p>These are the essential warrior skills. As a legend level <strong>pure</strong> warrior you would want to practice from the ranger guild master some</p>
<p><strong>wilderness-</strong> max it. this reduces move cost on foot, and reduces your need for foo</p>
<p><strong>dodge-&nbsp;</strong>as a pure warrior I would spend 5-10 pracs in dodge. 10 pracs will get you around 55% dodge with a base dex 16/per 13. That is&nbsp; +11 dodge bonus</p>
<p><strong>pick- </strong>I would advise around 3 pracs in pick.&nbsp;This will give you access to many more doors than not having it as well as the ability to set up traps etc. You may want to consider putting more than 3 pracs in this skill depending on what it is worth to you.</p>
<p><strong>attack-&nbsp;</strong>3 or so pracs in this skill. If you flee alot, or use a hit/flee tactic, the attack skill can come in very useful. I have spent only 3 pracs in attack and got it up to 41% and notice a difference in my fleeing. It is much faster. It is very useful against casters with charmies who order their charmie to ‘bash’. You can flee out much more easily and there is not so much risk in failing a flee and eating a bash and spells from the caster.</p>
<p>And if you wanted to make your character more of a <strong>combo</strong> or boost your damage a little, you could practice</p>
<p><strong>envenom-&nbsp;</strong>this skill can come as a great surprise to your enemies. Of course there is always the danger of poisoning yourself, but if you have some antidotes, you can quaff antidote and engage your enemy. If the poison does not take on the first try, flee out apply to poison to your weapon, and try again. I find the envenom skill to be of more use in <strong>combination with the missile skill</strong>. If you go with this option, you can prepare all of the arrows beforehand, and employ some bash/shoot. Then you do not have to reapply your poison to your weapon, only land a couple bashes and see if your arrows sink deep enough to administer the poison.</p>
<p><strong>missile-</strong>&nbsp;5 or 6 pracs with 16dex/13per will get your around 51% in missile. This is a very useful way to get some burst damage and increase your over all damage. However it is only really useful to a warrior if you are able to land a bash and fighting a single opponent as your missile skill is a delayed command that will be disrupted by being hit by other mobs or players. During the space of a bash you can usually land 1 or sometimes 2 <strong>weapon</strong> hits. But bows and arrows can land 2 or sometimes 3 arrows in the space of a bash, and arrows depending on the bow and arrow, can be more damaging, than your main weapon skill.&nbsp; This can be an excellent way to surprise your enemies and get them to awful or dead faster than they would have expected vs a pure warrior. As said, the major downfall of this is that with other players and mobs around, you may not be able to get your arrows off. Another major downfall is that it kind of depends on a bow that has high ob. If you dont have a good bow, and during the bash you can get off 3 arrows, but none of them hit the target, it is a complete waste of a bash. It would have been better to just wield your weapon and get the 1 or 2 hits you normally would have got. As a warrior I would probably only use a 30 ob bow, those are (chanted yew bow, embellished longbow, or elven longbow), and all of them are more easily obtained by the good races. If you want one you will have to kill a puke for it.</p>
<p>Finally, I have also seen some Zaugurz warriors who have practiced <strong>sneak</strong> or <strong>hide</strong> to avoid aggressive mobs and players while they regenerate move points and health points. It is worth a shot to try different practice sets, but you will not have enough practices to play around with until level 25, and it takes some doing to get there.</p>
<p><strong>comments-</strong> A final word on class choice. As a Zaugurz you will find yourself alone quite alot of the time. You will often pk and xp alone. As a lone warrior, you are limited to the mobs available to easily xp on. As a thief, xp and leveling will come much easier. Also, pk as a lone warrior is also rather difficult. You have no real burst damage to speak of and even if you track them down and come suddenly upon them, you still need to hit them to death at the speed of your weapon. You will need to be devious. You will have to have tricks up your sleeve. You will need to think about how to use the environment and surrounding mobs to your advantage. More often, if you are fighting, it is because people have tracked you down. Simply said, solo warrior can be brutal to play. They are much more dependent on eq and good eq for warriors is much more difficult to get. As a thief you can function well without too much eq and you can get eq much more easily. For these reasons, the Zaugurz find themselves short of pure warriors.</p>
<p><strong>Starting Out</strong></p>
<p>As a Zaugurz you start in a place called *the frozen north* and this is also where you go when you die. From here you can only “enter cart” to get you to the Zaugurz caves. The Zaugurz caves are not the safest place in the world. It has been known to be raided by puke scum or the weakling Tarkhnarb to the south, but it is where we call home, and you do feel relieved and safe enough to sleep when you finally come through the gates after a long journey. We have no dark tower (most of the time), vale tower (most of the time) no brolg, or tall orc, no demons, bloodthirsty orcs. No khuzur or redhorn caves. No safety of the warrens. There are some Zaugurz scouts on the trails leading north to the Zaugurz caves, but there are no other real friendly Zaugurz mobs outside of ZOC that will provide help in pk fights. There are some, but they are difficult to reach and out of the way. There is no relative safety to run to if you get into trouble. You have the choice to lose your hunters, to fight them, or to run to Z-orc caves.</p>
<p>As I have mentioned, you start out with no equipment so it is up to you find your first set of eq all by yourself. Sometimes there is extra eq in the room you land in after getting out of the cart. Sometimes there is eq in the crack in the rent place. There is a dagger that loads in the weapon rack in the Zaugurz caves and there is a source of water as well as some dried meat that you can find lying around, and sometimes there is a player around who could get you a giant spear or cruelly spiked mace or basic shield or some such.&nbsp; There are some black padded boots to the sw of the Zorc Caves on a path leading south of the main road through the Misty Mountains. I do not advise going after these boots if you are above level 1 and under level 10. As a level 1 it is fine if you mob die, but anything under 5 is risky because there are orc patrols, demon wolves, orc scouts, ferocious wargs, sometimes a cowled sorcerer, or a giant, and these mobs can kill you fast. Demon wolves, wargs, and orc patrols and giant will track you, so if you run out of moves you will die. Simply put, mob death is not worth the boots that may or may not load here.</p>
<p>If you are a new character/player regardless of the class, the first thing you will want to do as a Zaugurz is put <strong>almost all of your pracs in wilderness</strong>. Did I mention you get fewer pracs than all the other races? Oh well now you know, you get fewer pracs than all the other races. If you want you could put 1 or 2 pracs in swim, but apart from that I would make <strong>maxing wilderness a priority for the first few levels</strong> and then put pracs in swim and climb last of all. I consider <strong>wilderness</strong> the skill that most increases your survivability in the early levels. This is because it is the thing that will help your mobility the most early on. If you could ride, I would advise getting ride, or if you were close to easy xp early on then I could advise getting dodge, or parry, but those simply wont help you get out of the Misty Mountains to get to the areas where you need to get to in order to xp. <strong>Wilderness</strong> is the skill that can help most at early levels followed closely by swim, bandage and climb. I would put 3 pracs total into each swim, climb, and bandage by level 10 and slowly increase climb and swim as you gain levels. <strong>Wilderness</strong> reduces your move cost while on foot, as well as your need for food and water. Swim will become invaluable to you mostly as a means to lose mobs or players. The Anduin River is the Zaugurz second home, and you may find yourself jumping into the river quite often to escape your enemies. Because you cannot be tracked over running water, you can more easily lose those who are hunting you, and so increase your survivability.&nbsp; So if you are being chased or tracked, and you cant fight, you could just not engage and hope your enemy goes away, if not, you should try to find water to break your tracks, or slowly head back to Zorc caves, and sometimes the Zorc caves are just too far away so it is generally a good idea to max your swim skill to try and lose your hunters over water. For someone to track you after you have crossed some water, especially the Anduin River going downstream, well, it often takes more time and effort to track you than anyone is willing to give. Unless they call all the players online at any given moment to come track a Zaugurz who is far away from home and the safety of renting, and if everyone online is hunting you, which has been known to happen, well, you can say hello to *the frozen north* for me.</p>
<p>If you have practiced, you are now ready to adventure out of the caves. You can run around as much as you want as a level 1 without suffering horrible consequences when you die. If you die as a level 2 or level 5 you lose a level and have to gain all the xp back again to get to where you were. Mob dying is easily one of the most difficult and painful things about mume. However, mob dying as a level 1 is absolutely your best case scenario as far as mob dying goes. I would take advantage of this and travel out in search of “travel points”(tps) and equipment(eq). As a level 1, unless you know what you are doing and are confident, I would head east out of the Misty Mountains. Some advice on heading out. Only fight and move in shade or at night or indoors. You will lose more movement points while trying to move around in the sun. This is an easy way to find yourself moveless and dead. If you are moveless and the wrong mob or player walks into the room, you can say hello to *the frozen north* for me. When you fight in the sun you will be at a significant disadvantage because your offensive and defensive abilities are significantly reduced. For example a level 8 warrior fighting a black wolf in shade or at night is an easy win, fighting that same mob in sun will take much, much longer and be more difficult. You may not even find yourself winning. It is simply not worth your time to fight mobs or run around under the sun. If you do you will spend the valuable night hours regaining your health and movement points. Area knowledge is key, and you need to seek out the shady spots for rest and xp. All that to say, wait till the cover of night to leave the safety of the caves. <strong>Move in the dark, and fight in the dark.</strong></p>
<p>It is time I mention the cart. There is a cart in the Zaugurz caves. We use this cart to move equipment to the north. As you put equipment in the cart, you gain a kind of credit. With that credit, you can then ask for supplies and equipment from the frozen north. If you have carted up enough equipment, you can request a simple set of equipment, or a shield, or draughts etc. but as a level 1 it will be difficult for you to get enough credit to request even a simple set of equipment before you venture out from the caves. A common method of getting equipment to put in the cart is to lure orc patrols into ZOC. To do this though you have to let yourself get hit, and then leave a trail of fresh tracks leading to ZOC. The patrol will follow your tracks into the caves. You must however “unbar” the gate, and open it so that the orc patrol can enter. Then you simply let our own Zaugurz soldiers fight the fight, and loot all the equipment off all the dead orc patrol. You will take all the equipment to the cart and put it all in the cart. You then either “request” something, or simply “turn wheel” to send all the loot north. In this way you can build up credit, but it is not an effective way to gain xp or tps and it will not gain you levels, and as a level 1, you may or may not have enough hit points, or survival ability to lead the patrol up to the caves. Though as a level 1 it is no big deal if you mob die to the patrol, dying is still and always a setback, so it is better to avoid the patrols for the first few levels and simply focus on levels.</p>
<p>If you find an area with good xp, (the west side of the Anduin until the swamp to the south) you can gain the first few (4 or 5) levels very fast. It is easily possible to get to level 3 without any equipment whatsoever. Find foxes, rabbits/birds (only if you have a bow) fish, deer, etc. If you find yourself at level 3 or 5 and want to practice again, head back to ZOC, but travel only when it is night, and when you find yourself at half of your movement points you should rest until you are full and then proceed. If a patrol happens to come upon you and chase you, simply lead them up to the caves and loot them and get some credit. Like I have said put your pracs into wilderness and swim first, and then some climb, and then you can start practicing whatever you choose. I will mention that even for thieves, it is worthwhile leveling up as a warrior, because your backstab skill will not work very well until around 16-18 or so, so you may find that it is faster to level as a warrior. I would find yourself some absorb equipment, plate/heavy plate, a sword, or mace, or spear, and another low level that you can group together with.</p>
<p>Leveling as a group is so much faster, that both of you will appreciate it even if there is a level difference. I would say a level difference of 3 is ok, but 5 maybe getting to much of a difference. If I were trying to level up from level 1, I would try to get my first 5 or so levels done the first time I leave zoc. This way I can nearly max wilderness, and my hps/mps are higher, and I will be able to take a hit or two from a nasty mob. Still never go below half&nbsp;movement points (mps) so that when the nasty mob comes into the room, you can flee and have moves to run. I would advise that you dont panic and run too far too fast (especially in sun or when sneak is on) or you will find yourself moveless again, and waiting for the same mob to track you to death, or for something else to find you.</p>
<p>Well, that will take you to the first 5 levels or so and those will be your most fragile levels. You will continue the same pattern, that is waiting till night, running east, rest, xp there, or cross the river or jump into the river and find xp downstream. As you gain levels you can seek xp further to the south, and across the river to the north and south, and even into Mirkwood, though I would probably only enter Mirkwood around level 20. Remember that any time before level 26 you can get a partial reroll for your character after 1 real life month of retirement. This will let you adjust your base abilities a little bit. At levels 16-18 if you have the appropriate base abilities for a thief, you can repractice your character into a thief that can backstab. Also as you gain levels you will find yourself drawn to explore the western side of the Misties. Much more dangerous, but if you are so daring, maybe you will even kill some pukes or Tarkhnarb while you adventure.</p>
<p><strong>Some last warnings and hints</strong></p>
<p>– watch your moves!!! Be extra careful of moves while sneak is on. Moving with sneak and sun is a disaster waiting to happen. Be careful about taking on mobs in sun, especially groups of mobs in sun. The parry bonus of a shield is a must have. If you are a thief/stabber, check ‘info’ if your equipment weighs … heavy, but we will manage, get rid of other heavy equipment but keep the shield until you can find something lighter. If your equipment is heavier than ‘A tad uncomfortable, but no problem.’ then you may find yourself failing sneaks, or backstabs more often than not. Also the more you carry, the more you drain your mps as you move. As a thief, I would try to limit all the heavy equipment. Maybe only a few pieces of fine chain mail, but mostly plain pants/hood etc. If you can, always xp in a group, it helps everyone.</p>
<p>– people will play against what they think you are, so it is to your advantage to keep them guessing. If you backstabbed them once, and they are hanging around, they will be flushing/revealing, and that takes moves. They will be afraid to cure, or to track for fear you land another backstab. If you can enter the room they are in not sneaking, they will be in delay of revealing/flushing, and you can land some arrows, or try to land a bash. Then if they stop revealing/flushing, you could try to land a stabb again.</p>
<p><strong>Equipment</strong></p>
<p>I wrote before about getting some absorb eq for your warrior. Be aware that in general the more absorb an armor has, the heavier it is. The more you carry, the more move points you will drain as you move. Many choose to use the heavy and easily found absorb armor while xping, and then change to something lighter for their pk unless they have pretty good heavy eq. While you xp up you should do it in groups, and you will reduce your downtime if you fight at night, in shade, and with heavy absorb eq. What eq you wear is up to you and how you want to play. You may find that walking around with 120 lbs of fine metal weight all while on foot is far more dangerous than having less absorb, while still maintain the ability to move. It really depends on your play style. Some like to move around alot, some will be more local and will be able to take more damage.</p>
<p><strong>Black padded boots (-reduce move cost, slight armor)</strong>– corpse southwest of the Zaugurz caves and south of the main road through the misty mountains.</p>
<p><strong>Smooth black boots (-reduce move cost, no armor)</strong>– skeleton south of warrens</p>
<p><strong>Forest green cloak-(+5db, +move regen)</strong>-on eoggha, mountain of mirkwood corpse, elven home e of rivendell, corpse with rattlesnake by mrak near brolg. those are the closest.</p>
<p><strong>Weapons</strong> – as a Zaugurz many things are limited to you, that includes easy access to the normal set of damage dealing weapons. This is because enchanting a weapon will give it +10 ob and +2 damage. And there is no way to get weapons enchanted as a Zaugurz. So you are limited to a set of weapons that cannot be enchanted. Although enchanted orcish fang will do 2 more damage than unenchanted, and a enchanted fang is about as simple and easy as you can get in terms of a stabbing weapon for the other races, a Zaugurz cannot enchant it, so it is not worth going after as a Zaugurz, we must find a better dagger than unenchanted orcish fang even though all other thieves will get a orcish fang and enchant it and use it. The set of unenchanted good weapons that are available to a Zaugurz generally give only a +15 ob. I think the exceptions are an ornate warhammer, steel claymore, and some smiting weapons. The ones that are easily available will only have a +15 ob. These are discussed below.</p>
<p style="padding-left:30px;"><strong>Spears</strong> -Spears are great because they will automatically try to give you the first hit against all mobs that try to hit you. This feature is called Keep at Bay. If you enter a room and if there is an aggressive mob or player, and if they see you, they will try to hit you, but if you are wielding a spear, you automatically attempt to hit them when they try to hit you. It gives you a free hit, or the first hit, or it fails. You can ‘keep at bay’, flee to the next room, they will follow and try to hit again, and you could ‘keep at bay’ again. You could win against hard mobs this way, though it is costly on moves. Spears are&nbsp;also effective against people riding anything. Being Zaugurz, you will always be on foot, and your enemies, when they first find you, and if you are outdoors, will probably be riding. If you let them try to hit you first, the odds are in your favor that you will hit them first, and they will be hit hard because all spear weapons are effective against anything that is riding. If they realize you are using a spear, they will have to choose to fight on foot and lose more moves, or stay on the horse and lose more hps. Other races will not be as used to managing their mps as you, and they will hopefully spam their moves away. Being moveless is a step away from being dead, especially for a puke in the misty mountains. All that to say spears are a good choice.</p>
<p style="padding-left:30px;"><strong>giant spear (+15ob,-5pb)</strong>&nbsp;– loads on the burly giant a little south of the Zorc caves. It loads on a level 15 or so mob. Even though blackened spear (+20ob) is the best spear weapon, and it is non-enchantable, it is not available to the Zaugurz because it is made of 3 items, and while we Zaugurz can gather the items, there is no mob to make the spear for us. The mobs that make the blackened spears for the other races are aggressive to us. If you want a blackened spear you will have to take it out of the hands of your dead enemy. And not many people use blackened spear as a weapon. Maces and axes are more popular, or swords and daggers for those more defensively minded.</p>
<p><strong>Axes</strong> -Axes deal alot of damage and are pretty quick. Axes will be a good choice for us, but they are more difficult to get a hold of than the giant spear.</p>
<p style="padding-left:30px;"><strong>mighty dwarven axe(MDA +15ob,-5pb)</strong> – it is doubtful you could get one solo. It loads in eregion, in some dwarven tombs east of ost-in-edhel and west of tall orc, and north of the road. You would be hard pressed to get it as a solo warrior, but two could work to get it. A solo thief might be able to get it, I have not yet tried though.</p>
<p style="padding-left:30px;"><strong>Darkened orcish axe(+15ob,-5pb)</strong> – more damage than MDA, and better in my opinion. this axe might be easier to get for a solo warrior orc, but you have to enter fangorn forest, and the whole place is aggressive to all orcs. And it is believed that the forest tracks orcs who enter. It is also quite a hike from zoc. It is stuck in the back of an ent in the middle part of the forest and max north. You will have to kill the ent quickly and likely many other trees and mobs. Good xp, but you also might mobdie. I have never acquired it as an orc.</p>
<p><strong>Concussion weapons</strong> – a good one is tougher to come by. Many players like to use crushing weapons because they are effective against those wearing metal. Meaning more damage done, and metal armors are fairly common. So if you have a crushing weapon, the odds are in your favor in terms of increased damage against many others.</p>
<p style="padding-left:30px;"><strong>ornate warhammer(ornate +20ob,-5pb)</strong> – It loads on a mob in Moria. I play mostly solo, and have rarely explored Moria, and if I were to explore it I would do it solo as a thief and as a thief I would not really need ‘ornate’ as a main weapon and it loads on a super mob. So unless you have a group, it is probably easier to go after a puke, and as crushing weapons are the favorite amongst warriors, your best bet is to track down or lure someone, kill them and take theirs.</p>
<p style="padding-left:30px;"><strong>engraved warhammer(+20ob,-5pb)</strong> – Loads on spirit knight some nw of malardil and tbad.&nbsp; Can be soloed by thief, and warrior (I beat it solo with puke warrior by hit/flee with smiting weapon) target the slaves first. This may be the easiest cheapest weapon to get in this class.</p>
<p style="padding-left:30px;"><strong>cruelly spiked mace(+15ob,-5pb)</strong> – this will not do as much damage as those above, but it is far faster of a weapon, and still effective against metal, and you do not have to enchant it. I have seen it load on the orcish patrol leaders that roam south or west of zoc. This should be a decently easy weapon to find for any Zaugurz.</p>
<p><strong>Daggers</strong> – this is the must have weapon for the thieves and scouts who will get their kills with backstabs.</p>
<p><strong>Black Runed Dagger(BRD)&nbsp;</strong>– this is the best in-class weapon for all thieves and many caster characters. It loads on the BN sage in the Redhorn Caves. It would be hard to get, as you have to raid first to find out if the BRD has even loaded on him. And the Redhorn caves are costly to get to in terms of movement, especially for Zaugurz. It is in the middle of snow and mountains, and has aggressive mobs and players all around. It will be easier to take this of someones corpse than to get it from the mob who loads it.</p>
<p><strong>Barbed Fang</strong> –</p>
</div>
</div>
</div>
</div>
</body>
</html>
